<a href="https://colab.research.google.com/github/Keruthika-N/Milestone-1/blob/main/dwdm(random_forest).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/AD_all_patients.csv')
df.head()

,Fp1,Fp2,F7,F3,Fz,F4,F8,T3,C3,Cz,C4,T4,T5,P3,Pz,P4,status
0,116.99375,41.09375,66.69375,-64.50625,-126.40625,8.39375,22.49375,42.19375,53.29375,4.49375,2.49375,73.79375,129.29375,0.09375,-124.90625,-245.50625,1
1,115.93125,38.63125,64.73125,-64.66875,-125.26875,8.73125,27.03125,43.23125,57.53125,11.13125,2.33125,72.23125,125.73125,-5.46875,-123.06875,-248.76875,1
2,115.72500,38.32500,66.02500,-62.67500,-135.37500,9.02500,29.42500,47.12500,49.92500,24.42500,1.22500,72.92500,123.22500,-3.07500,-129.97500,-246.27500,1
3,120.15625,40.75625,71.05625,-59.54375,-148.34375,12.15625,32.25625,49.05625,41.05625,12.75625,1.85625,73.55625,128.65625,-0.14375,-133.24375,-242.04375,1
4,119.50000,39.50000,71.30000,-59.20000,-125.50000,14.80000,28.50000,48.80000,42.20000,-1.20000,1.40000,70.30000,116.10000,3.40000,-129.00000,-240.90000,1

In [ ]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848640 entries, 0 to 848639
Data columns (total 17 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Fp1     848640 non-null  float64
 1   Fp2     848640 non-null  float64
 2   F7      848640 non-null  float64
 3   F3      848640 non-null  float64
 4   Fz      848640 non-null  float64
 5   F4      848640 non-null  float64
 6   F8      848640 non-null  float64
 7   T3      848640 non-null  float64
 8   C3      848640 non-null  float64
 9   Cz      848640 non-null  float64
 10  C4      848640 non-null  float64
 11  T4      848640 non-null  float64
 12  T5      848640 non-null  float64
 13  P3      848640 non-null  float64
 14  Pz      848640 non-null  float64
 15  P4      848640 non-null  float64
 16  status  848640 non-null  int64
dtypes: float64(16), int64(1)
memory usage: 110.1 MB

Fp1       0
Fp2       0
F7        0
F3        0
Fz        0
F4        0
F8        0
T3        0
C3        0
Cz        0
C4        0
T4        0
T5        0
P3        0
Pz        0
P4        0
status    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(1036)

In [ ]:
df = df.drop_duplicates()

In [ ]:
#outlier handling
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df < (Q1 - 1.5 * IQR)) | (df > (Q3 + 1.5 * IQR))).any(axis=1)]

In [ ]:
X = df.drop('status', axis=1)
y = df['status']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9983074082363473

In [ ]:
print(df['status'].value_counts())

status
1    197606
0    159833
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     31858
           1       1.00      1.00      1.00     39630

    accuracy                           1.00     71488
   macro avg       1.00      1.00      1.00     71488
weighted avg       1.00      1.00      1.00     71488

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[31790    68]
 [   53 39577]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     31858
           1       1.00      1.00      1.00     39630

    accuracy                           1.00     71488
   macro avg       1.00      1.00      1.00     71488
weighted avg       1.00      1.00      1.00     71488